# Generated by Django 4.1 on 2025-02-14 12:29

import cinema.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=cinema.utils.create_custom_path),
        ),
    ]
